### PR TITLE
more backups remain on the disk

### PR DESCRIPTION
**Pull request by lotharschulz**

### CODE REVIEW

**Comment by lotharschulz** [comment]
@jmcs : pls check

**Comment by lotharschulz** [comment]
https://travis-ci.org/zalando/ghe-backup/builds/156868372: should have run tests on the first month of a month earlier

**Comment by lotharschulz** [comment]
https://travis-ci.org/zalando/ghe-backup/builds/156878354 looks better

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
