### PR TITLE
Update maintainers

### PR DESCRIPTION
**Pull request by rashamalek**
Update maintainers 
+serhii.cherniavskyi
+rasha malek

### CODE REVIEW

**Comment by hjacobs** [comment]
Remove Lothar?

**Comment by rashamalek** [comment]
@hjacobs makes sense as the email is not valid.
@lotharschulz please feel free to add your new email if you are still interested in maintaining this repo

**Comment by hjacobs** [comment]
:+1:

**Comment by rashamalek** [comment]
👍

**Pull request merged**
