### PR TITLE
log file and logrotation

### PR DESCRIPTION
**Pull request by lotharschulz**
*WIP*

ref: https://github.com/zalando/ghe-backup/issues/51

- replaces the fifo with a logfile
- logrotation using [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html)

### CODE REVIEW

**Comment by tuxlife** [comment]
Please save the log file in the EBS Backup Volume and not in the docker image (/var/log)

**Comment by lotharschulz** [comment]
Well, in case the EBS gets unmounted logs are still available locally. On the other hand the EBS has much more capacity of course. @tuxlife : do you see more points to consider?

**Comment by tuxlife** [comment]
log rotation doesn't work in a docker file. The files are not really deleted. There are not viewable from docker it self.

**Comment by rashamalek** [comment]
@lotharschulz @tuxlife As tested, each log file would be ~ 3-4 MB, what about keeping them on ELB volume, it make sense to keep the logs beside backup on the ELB.
something similar to
```
/backup/backup-utils/bin/ghe-backup -v 1>> /data/ghe-production-data/backup-`date +%Y%m%d-%H%M%S`.log
```

**Comment by lotharschulz** [comment]
that should be combined with tee to have the output on std out like
```
/backup/backup-utils/bin/ghe-backup |& tee 1>> /data/ghe-production-data/backup-`date +%Y%m%d-%H%M%S`.log
```
pls note: no `-v` to reduce the original log file size.

**Comment by rashamalek** [comment]
@lotharschulz tested without -v, Log size would reduce to less than 1K, wondering if removing fifo is needed anymore. I guess without -v the buffer will not be full anymore.

**Comment by lotharschulz** [comment]
lets give this a try then, will open another PR and notify you

**Comment by lotharschulz** [comment]
https://github.com/zalando/ghe-backup/pull/54 removes the verbose flag, pls 👍  this

**Comment by rashamalek** [comment]
👍

**Comment by rashamalek** [comment]
#54 would remove the verbose flag, not #53

**Comment by lotharschulz** [comment]
- not needed for #51
- close this but leave the branch for later reference

**Pull request closed without merging**
