### PR TITLE
docker tag including cdp build version and target repo counter

### PR DESCRIPTION
**Pull request by lotharschulz**
ref: #66
particular ref: https://github.com/zalando/ghe-backup/issues/66#issuecomment-312864315

docker tag including cdp build version and target repo counter for unique tags

### CODE REVIEW

**Comment by lotharschulz** [comment]
👍

**Comment by rashamalek** [comment]
👍

**Comment by lotharschulz** [comment]
https://github.com/zalando/ghe-backup/pull/72/commits/dda1b291e2a13844ac5fe76a9cb832e0169285bd cdp build succeeds

**Comment by lotharschulz** [comment]
👍

**Comment by rashamalek** [comment]
👍

**Comment by lotharschulz** [comment]
👍

**Comment by lotharschulz** [comment]
👍

**Review by jmcs — COMMENTED** [review]
:+1:

**Comment by lotharschulz** [comment]
👍

**Comment by lotharschulz** [comment]
cdp build succeeded

**Comment by dryewo** [comment]
👍

**Pull request merged**
