### PR TITLE
feat: support BACKUP_UTILS_VERSION during build

### PR DESCRIPTION
**Pull request by kgalli**
Supporting the `backup-utils` version to be set during the Docker build step enables users to have their GitHub Enterprise version in lock step with the actual `backup-utils` version instead of always taking latest
stable.

To play nice the default of using stable is kept in place.

### CODE REVIEW

**Comment by kgalli** [comment]
👍

**Comment by monicagangwar** [comment]
👍🏼

**Comment by monicagangwar** [comment]
👍

**Comment by kgalli** [comment]
👍

**Comment by M4NTR4** [comment]
:+1:

**Comment by kgalli** [comment]
👍

**Comment by M4NTR4** [comment]
:+1:

**Pull request merged**
