### PR TITLE
create SECURITY.md

### PR DESCRIPTION
**Pull request by lotharschulz**
create a SECURITY.md file

### CODE REVIEW

**Comment by lotharschulz** [comment]
👍

**Comment by rashamalek** [comment]
👍

**Comment by lotharschulz** [comment]
👍

**Comment by lotharschulz** [comment]
need again 👍 after [merge commit](https://github.com/zalando/ghe-backup/pull/68/commits/d14b1819d6285edb33e99fe782ebb2bccbc1e9c1) .

**Comment by rashamalek** [comment]
👍

**Pull request merged**
